export interface Resource {
  id: number
  subject: string
  code: string
  branch: string
  semester: string
  type: 'Notes' | 'PYQ' | 'Important Qs' | 'Lab Manual' | 'Syllabus' | 'Books'
  uploader: string
  year: string
  downloads: number
  rating: number
  tags: string[]
  color: string
  description: string
  link: string
  featured?: boolean
  trending?: boolean
  new?: boolean
}

export const branches = ['All', 'CSE', 'IT', 'ECE', 'ICE', 'ENE', 'MAE']
export const semesters = ['All', '1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th']
export const resourceTypes = ['All', 'Notes', 'PYQ', 'Important Qs', 'Lab Manual', 'Syllabus', 'Books']

export const typeColors: Record<string, { bg: string; text: string }> = {
  'Notes':        { bg: '#FF4444', text: '#fff' },
  'PYQ':          { bg: '#FFB800', text: '#000' },
  'Important Qs': { bg: '#00C853', text: '#fff' },
  'Lab Manual':   { bg: '#2979FF', text: '#fff' },
  'Syllabus':     { bg: '#E040FB', text: '#fff' },
  'Books':        { bg: '#FF6D00', text: '#fff' },
}

export const typeEmoji: Record<string, string> = {
  'Notes':        '📝',
  'PYQ':          '📋',
  'Important Qs': '⭐',
  'Lab Manual':   '🔬',
  'Syllabus':     '📚',
  'Books':        '📖',
}

export const resources: Resource[] = [
  {
    id: 1,
    subject: 'Data Structures & Algorithms',
    code: 'CS-201',
    branch: 'CSE',
    semester: '3rd',
    type: 'Notes',
    uploader: 'Priya S.',
    year: '2024',
    downloads: 1247,
    rating: 4.8,
    tags: ['DSA', 'Trees', 'Graphs', 'DP'],
    color: '#FF4444',
    description: 'Complete handwritten notes covering all 5 units with diagrams, examples and code snippets.',
    link: '#',
    featured: true,
    trending: true,
  },
  {
    id: 2,
    subject: 'Operating Systems',
    code: 'CS-301',
    branch: 'CSE',
    semester: '5th',
    type: 'PYQ',
    uploader: 'Ananya R.',
    year: '2024',
    downloads: 892,
    rating: 4.6,
    tags: ['OS', 'Scheduling', 'Memory', 'Deadlock'],
    color: '#FFB800',
    description: 'Last 10 years PYQs compiled with detailed model answers and marking scheme.',
    link: '#',
    trending: true,
  },
  {
    id: 3,
    subject: 'Database Management Systems',
    code: 'CS-303',
    branch: 'CSE',
    semester: '5th',
    type: 'Important Qs',
    uploader: 'Shreya M.',
    year: '2024',
    downloads: 673,
    rating: 4.7,
    tags: ['SQL', 'Normalization', 'Transactions', 'ER'],
    color: '#00C853',
    description: 'Curated list of high-weightage questions from all units with expected detailed answers.',
    link: '#',
    featured: true,
  },
  {
    id: 4,
    subject: 'Digital Electronics',
    code: 'EC-201',
    branch: 'ECE',
    semester: '3rd',
    type: 'Lab Manual',
    uploader: 'Kavya T.',
    year: '2024',
    downloads: 445,
    rating: 4.5,
    tags: ['Logic Gates', 'Flip Flops', 'Counters', 'Mux'],
    color: '#2979FF',
    description: 'Complete lab manual with circuit diagrams, observations tables, and viva questions.',
    link: '#',
  },
  {
    id: 5,
    subject: 'Mathematics - III',
    code: 'MA-301',
    branch: 'CSE',
    semester: '5th',
    type: 'Notes',
    uploader: 'Divya K.',
    year: '2023',
    downloads: 1089,
    rating: 4.9,
    tags: ['Transforms', 'Complex Analysis', 'PDE', 'Fourier'],
    color: '#FF4444',
    description: 'Detailed typed notes with 100+ solved examples, shortcut tricks and common mistakes.',
    link: '#',
    trending: true,
  },
  {
    id: 6,
    subject: 'Computer Networks',
    code: 'CS-401',
    branch: 'IT',
    semester: '7th',
    type: 'PYQ',
    uploader: 'Riya P.',
    year: '2024',
    downloads: 534,
    rating: 4.4,
    tags: ['TCP/IP', 'Routing', 'Protocols', 'OSI'],
    color: '#FFB800',
    description: '7-year PYQs with step-by-step solutions and important topic highlights.',
    link: '#',
  },
  {
    id: 7,
    subject: 'Signals & Systems',
    code: 'EC-301',
    branch: 'ECE',
    semester: '4th',
    type: 'Syllabus',
    uploader: 'Meera J.',
    year: '2024',
    downloads: 312,
    rating: 4.3,
    tags: ['Fourier', 'Laplace', 'Z-Transform', 'Convolution'],
    color: '#E040FB',
    description: 'Updated 2024 syllabus with chapter-wise weightage and recommended reading list.',
    link: '#',
  },
  {
    id: 8,
    subject: 'Machine Learning',
    code: 'CS-501',
    branch: 'CSE',
    semester: '7th',
    type: 'Books',
    uploader: 'Tanvi S.',
    year: '2024',
    downloads: 789,
    rating: 4.7,
    tags: ['Supervised', 'Neural Nets', 'Python', 'Sklearn'],
    color: '#FF6D00',
    description: 'Curated reference books, research papers, and Jupyter notebooks for the full syllabus.',
    link: '#',
    featured: true,
  },
  {
    id: 9,
    subject: 'Control Systems',
    code: 'ICE-301',
    branch: 'ICE',
    semester: '5th',
    type: 'Notes',
    uploader: 'Sneha A.',
    year: '2024',
    downloads: 367,
    rating: 4.6,
    tags: ['Bode Plot', 'Root Locus', 'PID', 'Nyquist'],
    color: '#FF4444',
    description: 'Handwritten notes with detailed transfer function examples and stability analysis.',
    link: '#',
  },
  {
    id: 10,
    subject: 'Thermodynamics',
    code: 'MAE-201',
    branch: 'MAE',
    semester: '3rd',
    type: 'PYQ',
    uploader: 'Pallavi N.',
    year: '2024',
    downloads: 298,
    rating: 4.5,
    tags: ['Laws', 'Entropy', 'Cycles', 'Heat Transfer'],
    color: '#FFB800',
    description: 'Previous years numerical questions solved step-by-step with unit analysis.',
    link: '#',
  },
  {
    id: 11,
    subject: 'Engineering Mathematics - I',
    code: 'MA-101',
    branch: 'CSE',
    semester: '1st',
    type: 'Notes',
    uploader: 'Aisha K.',
    year: '2024',
    downloads: 2156,
    rating: 4.9,
    tags: ['Calculus', 'Matrices', 'Series', 'Differential Equations'],
    color: '#FF4444',
    description: 'Most downloaded first-year notes — perfect for absolute beginners with visual explanations.',
    link: '#',
    featured: true,
    trending: true,
    new: true,
  },
  {
    id: 12,
    subject: 'Python Programming',
    code: 'CS-102',
    branch: 'IT',
    semester: '2nd',
    type: 'Lab Manual',
    uploader: 'Kriti M.',
    year: '2024',
    downloads: 1456,
    rating: 4.8,
    tags: ['Python', 'OOP', 'Functions', 'File I/O'],
    color: '#2979FF',
    description: 'Complete 30-program lab manual with sample outputs, viva Q&A and bonus programs.',
    link: '#',
    trending: true,
    new: true,
  },
  {
    id: 13,
    subject: 'Electromagnetic Field Theory',
    code: 'EC-401',
    branch: 'ENE',
    semester: '5th',
    type: 'Notes',
    uploader: 'Pooja V.',
    year: '2024',
    downloads: 234,
    rating: 4.4,
    tags: ['Maxwell', 'Wave Propagation', 'Antennas'],
    color: '#FF4444',
    description: 'Comprehensive notes with vector calculus refresher and application examples.',
    link: '#',
  },
  {
    id: 14,
    subject: 'Design & Analysis of Algorithms',
    code: 'CS-401',
    branch: 'CSE',
    semester: '6th',
    type: 'Important Qs',
    uploader: 'Nisha B.',
    year: '2024',
    downloads: 567,
    rating: 4.7,
    tags: ['Greedy', 'Backtracking', 'NP-Hard', 'Complexity'],
    color: '#00C853',
    description: 'Exam-oriented important questions with time & space complexity analysis included.',
    link: '#',
    new: true,
  },
  {
    id: 15,
    subject: 'Computer Organization & Architecture',
    code: 'CS-302',
    branch: 'IT',
    semester: '5th',
    type: 'Books',
    uploader: 'Simran D.',
    year: '2024',
    downloads: 412,
    rating: 4.5,
    tags: ['Pipeline', 'Cache', 'Assembly', 'ISA'],
    color: '#FF6D00',
    description: 'Standard textbooks + IGDTUW-specific handouts curated by senior students.',
    link: '#',
  },
]
